[package]
name = "ws-tool"
version = "0.3.0"
authors = ["PrivateRookie <996514515@qq.com>"]
edition = "2018"
description = "an easy to use websocket tool"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/PrivateRookie/ws-tool"
repository = "https://github.com/PrivateRookie/ws-tool"
keywords = ["websocket", "proxy", "network"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
tokio = { version = "1", features = ["rt", "net", "io-util"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio-rustls = "0.22"
webpki = "0.21"
webpki-roots = "0.21"
thiserror = "1"
rand = "0.8"
base64 = "0.13"
tracing ="0.1"
bytes = "1"
rcgen = "0.8"
httparse = "1.4"
sha-1 = "0.9"
tokio-socks = "0.5"
async-http-proxy = { version = "1", features = ["runtime-tokio"] }
tokio-stream = "0.1"
futures = "0.3"
serde = "1"


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2"
structopt = "0.3"
rcgen = "0.8"
