[package]
name = "ws-tool"
version = "0.3.1"
authors = ["PrivateRookie <996514515@qq.com>"]
edition = "2018"
description = "an easy to use websocket tool"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/PrivateRookie/ws-tool"
repository = "https://github.com/PrivateRookie/ws-tool"
keywords = ["websocket", "proxy", "network"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
tokio = { version = "1", features = ["rt", "net", "io-util"] }
tokio-util = { version = "0.6", features = ["codec"] }
thiserror = "1"
rand = "0.8"
base64 = "0.13"
tracing = "0.1"
bytes = "1"
httparse = "1.4"
sha-1 = "0.9"
tokio-stream = "0.1"
futures = "0.3"
serde = "1"

# tls deps
tokio-rustls = { version = "0.22", optional = true }
webpki = { version = "0.21", optional = true }
webpki-roots = { version = "0.21", optional = true }

# proxy deps
tokio-socks = { version = "0.5", optional = true }
async-http-proxy = { version = "1", features = [
    "runtime-tokio",
], optional = true }

# deflate deps
flate2 = { version = "1", optional = true }

[features]
default = []
proxy = ["tokio-socks", "async-http-proxy"]
rustls = ["tokio-rustls", "webpki", "webpki-roots"]
deflate = ["flate2"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2"
structopt = "0.3"
rcgen = "0.8"


[[example]]
name = "echo"
required-features = ["rustls", "proxy"]

[[example]]
name = "binance"
required-features = ["rustls", "proxy"]

[[example]]
name = "split_binance"
required-features = ["rustls", "proxy"]
